version: "3"
services:

  server:
   build: ./server
   expose: 
   - ${APP_SERVER_PORT }
   enviroment:
   API_HOST: ${API_HOST}
   APP_SERVER_PORT: ${APP_SERVER_PORT}
  ports:
  - ${APP_SERVER_PORT} : ${APP_SERVER_PORT}
  volumes :
  - ./server/src:/server/src/app

  command : npm run start:dev


  client:
   build : ./frontend
   enviroment:
   - ${APP_PORT}=${APP_PORT}
   expose: 
    - ${APP_PORT}
   ports:
    - ${APP_SERVER_PORT} : ${APP_SERVER_PORT}
volumes:
    - ./frontend/src: frontend/src/app
    - ./frontend/src: dist/main
links:
    - server
command : npm run start:dev